version: '2'
services:
  ruby:
    restart: unless-stopped
    image: 'ghcr.io/ruby-network/ruby:latest'
    ports:
      #DO NOT CHANGE 9293!
      - 9293:9293
    volumes:
      - ./config.yml:/usr/src/app/config/settings.yml
#networks:
  #  default:
  #    external:
  #      name: default_net
